#define kNavigationBarBackgroundImageTag                6183746


#define VIDEO_FEED_DOWNLOAD_COMPLETED_NOTIFICATION      @"VIDEO_FEED_DOWNLOAD_COMPLETED_NOTIFICATION"
#define SEARCH_RESULT_DOWNLOAD_COMPLETED_NOTIFICATION   @"SEARCH_RESULT_DOWNLOAD_COMPLETED_NOTIFICATION"
#define SEARCH_COMPLETED_NOTIFICATION                   @"SEARCH_COMPLETED_NOTIFICATION"
#define SUGGESTION_COMPLETED_NOTIFICATION               @"SUGGESTION_COMPLETED_NOTIFICATION"
#define START_SEARCHING_NOTIFICATION                    @"START_SEARCHING_NOTIFICATION"