#define kNavigationBarBackgroundImageTag                6183746

#define VIDEO_FEED_DOWNLOAD_COMPLETED_NOTIFICATION      @"VIDEO_FEED_DOWNLOAD_COMPLETED_NOTIFICATION"
#define VIDEO_POSTER_TAPPED_NOTIFICATION                @"VIDEO_POSTER_TAPPED_NOTIFICATION"